### ISSUE TITLE
To remove the <br> tag

### ISSUE THREAD

**Issue by moloimaga12** [philbuchanan/Accordion-Shortcodes#33]
can you give me a hint on how i can remove the <br></br>.

thank you

**Comment by philbuchanan** [comment]
This is unfortunately not an issue I can address in the plugin. It has to do with `wpautop` in WordPress. WordPress tends to want to wrap paragraph and break tags around shortcodes. You can get around this by adding this code to your themes `functions.php` file:

	/**
	 * Fixes empty <p> and <br> tags showing before and after shortcodes in the
	 * output content.
	 */
	function pb_the_content_shortcode_fix($content) {
		$array = array(
			'<p>['    => '[',
			']</p>'   => ']',
			']<br />' => ']',
			']<br>'   => ']'
		);
		$content = strtr($content, $array);
		
		return $content;
	}
	add_filter('the_content', 'pb_the_content_shortcode_fix');

**Comment by moloimaga12** [comment]
thanks alot sir...i will try what you suggest....

God bless

On Wed, Mar 18, 2015 at 11:06 AM, Phil Buchanan <notifications@github.com>
wrote:

> Closed #33
> <https://github.com/philbuchanan/Accordion-Shortcodes/issues/33>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/philbuchanan/Accordion-Shortcodes/issues/33#event-257660190>
> .
>



-- 

*Romulo G. Maga Jr.*
(02) 781-1804 / +639058707678
