### ISSUE TITLE
Nested accordions does not work

### ISSUE THREAD

**Issue by JohnMidity** [philbuchanan/Accordion-Shortcodes#40]
An accordion inside an accordion item does not work.

```html
[accordion]
    [accordion-item title="1"]one[/accordion-item]
    [accordion-item title="a-z"]
        [accordion]
            [accordion-item title="a"]a[/accordion-item]
            [accordion-item title="b"]b[/accordion-item]
        [/accordion]
    [/accordion-item]
[/accordion]
```
This results in a stray ```[/accordion-item] [/accordion]``` on the page and a badly working accordion.

**Comment by philbuchanan** [comment]
This is a limitation of WordPress and how it parses for shortcodes.

**Comment by postmastersteve** [comment]
What about supporting nested accordions with another name? Such as with the compatibility mode prefix already supported? (e.g. [as-accordion])
I only need to add a second level - is there really no way around this?

**Comment by philbuchanan** [comment]
Technically it could be possible to add additional shortcodes with different names that would support this, but it would add considerable complexity to the plugin. I also wound not recommend it from a UX perspective. 

This plugin is not meant to solve all problems that all users have. If you really need nesting of accordions I suggest looking into other plugins.
