### ISSUE TITLE
Clicking and having it open another place on the same page.

### ISSUE THREAD

**Issue by paaljoachim** [philbuchanan/Accordion-Shortcodes#50]
Hi

It seems your plugin is able to make accordions - or perhaps rather just a link and then have it open another place on the page.

Right now I am working on Oslo Spiritual Film Clubs web site. The following page is a wireframe from the movie of the month page showing a poster bottom left, above various titles that can be clicked. For each title that is clicked info sections are seen to the right below where it says Dreams of Damanhur.

![maanedens-film-oslo-spirituelle-filmklubb](https://cloud.githubusercontent.com/assets/5323259/12372772/d4073f52-bc62-11e5-8224-336b5def8224.jpg)

I have a feeling that I can do these things with your plugin but am not sure how to accomplish this. If you can give some headsup that would be great. Perhaps even add some info into the WP repo for doing this as well.

Have a great weekend!

**Comment by paaljoachim** [comment]
I am getting it to work by using:

symbolsynopis - link
symbol tech -link


[accordion autoclose="true" openfirst="false" openall="false" scroll="true" ]

[accordion-item id="synopsis" title=" "]
Info about the movie...
[/accordion-item]

[accordion-item id="tech" title=" "]
Technical info
How long?
Director?
Actors?
[/accordion-item]
[/accordion]

Right now I am looking at further customizations then what is listed.

Even if I set [accordion autoclose="true" openfirst="true" openall="false" scroll="false" ]  Scroll to false it jumps down on the page. I just want it to stay in place.

**Comment by philbuchanan** [comment]
I'm not sure I completely understand what you are trying to achieve. It sounds like you want the accordion titles contained in one column on the left (above the poster) and the accordion content in a separate column on the right. If that is the case, it's not really how the plugin was intended to be used. I'm not entirely sure how you would get that working.

**Comment by paaljoachim** [comment]
Links on the left - content on the right.

It is a way to make the page smaller by having links on the left. By clicking these the info for that link shows up in an location on the right. 

I have got it working but clicking a link pushes the page to the bottom. I just want to keep it where it is. There is also an accordion animation that I want to remove.

**Comment by philbuchanan** [comment]
The jumping will happen because of the hash change in the URL. And the animation is baked into the plugin. There will be no easy way to remove that without significantly modifying the plugin code. As I mentioned before, this is really not the intended usage of this plugin so you may be better served with another plugin.

**Comment by paaljoachim** [comment]
I am getting it to look nice!
http://spirituellfilm.no/nestefilm/

Any one issue is that a thin grey line pops up that I am having a hard time removing. So I put some orange lines in there instead.

**Comment by philbuchanan** [comment]
Looks like it's working out well for you. The border looks like a weird rendering issue. As soon as I move my mouse over it, it disappears.

**Comment by paaljoachim** [comment]
Yeah I know. I have not found a solution to it yet.

**Comment by paaljoachim** [comment]
I was able to add white lines and it now looks a lot better.
I still have the problem of the click a link and it jumps to the bottom of the page.
How can I hack your plugin to make it stop jumping to the bottom?
Btw this can very well be a new feature in your plugin..:)

**Comment by philbuchanan** [comment]
The jump is happening because of how you are using `#` in your URLs. It is a built in feature of all browsers and is not a result of any code in my plugin.
