### ISSUE TITLE
Conflicting with a theme

### ISSUE THREAD

**Issue by teej043** [philbuchanan/Accordion-Shortcodes#55]
I really want to use this, pretty easy to customize however, the client is using this theme https://themeforest.net/item/modernize-flexibility-of-wordpress/1264247 which conflicts with your plugin as it also has its own accordion shortcode. I just wonder why it conflicts when you use the plugin shortcode as if the theme is calling its own shortcode and mess out the render (wherein markup is produced by the theme's own accordion shortcode instead of the accordion-shortcode plugin).

**Comment by philbuchanan** [comment]
See **Compatibility Mode** on the [other notes page](https://wordpress.org/plugins/accordion-shortcodes/other_notes/) of the plugin. This will change the default shortcode name that the plugin uses.
