### ISSUE TITLE
Accessibility box around menu option displays when option is clicked

### ISSUE THREAD

**Issue by ogagliardi** [philbuchanan/Accordion-Shortcodes#61]
After updating to the latest release I noticed that there is now an accessibility box (in blue) displayed when a menu option is selected. How can I turn of this highlight?

Thanks.

**Comment by ogagliardi** [comment]
I found your readme file :) I live the issue here in case someone else encounters the same problem:

.accordion-title {outline: none;}

**Comment by philbuchanan** [comment]
It was added in the most recent release to accommodate better accessibility. The code above is the solution if you don't want to see the focus highlight, however it is generally recommended that you have _some_ focus state for users navigating your site via keyboard.
