### ISSUE TITLE
Conflicting shortcode name

### ISSUE THREAD

**Issue by rasedulhasan** [philbuchanan/Accordion-Shortcodes#80]
Hi

My theme already offers the same functionality (which I am trying to get rid of by using an independent plugin) with the same shortcode name [accordion]. So it is conflicting with the theme and not showing anything.

Can you make the shortcode name independent? e.g. [my-accordion]?

Thanks!

**Comment by philbuchanan** [comment]
If you refer to the [Plugin documentation](https://wordpress.org/plugins/accordion-shortcodes/), you'll see that there is a compatibility mode where you can add `define('AS_COMPATIBILITY', true);` to the `wp-config.php` file to change the shortcode name to `[as-accordion]`. I recommend suggesting users of your theme use that option or another plugin. I will not be able to change the shortcode name globally as doing so will break thousands of existing website installations.
